[package]
edition = "2021"
name = "crossterm"
version = "0.1.0"

[dependencies]
crossterm = {version = "0.25", features = ["event-stream"]}
tokio = {version = "1.25.0", features = ["sync", "rt-multi-thread", "macros"]}
tui = "0.19.0"
tui-elm = {path = "../.."}
