[package]
edition = "2021"
name = "elm-tui-tester"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elm-ui = {path = "../elm-ui"}
tokio = "1.26.0"
tui = "0.19.0"
