on: [push]
name: CI
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cache-${{ hashFiles('**/Cargo.toml') }}
      - name: Test
        run: |
          cargo build
          (cd examples/termion && cargo build)
          (cd examples/fltk && cargo build)
