on: [push]
name: CI
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cache-${{ hashFiles('**/Cargo.toml') }}
      - name: Test
        run: |
          sudo apt-get update && sudo apt-get install -y libpango1.0-dev libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libpng-dev libgl1-mesa-dev libglu1-mesa-dev
          cargo build
          (cd crates/elm-ui/examples/termion && cargo build)
          (cd crates/elm-ui/examples/crossterm && cargo build)
          (cd crates/elm-ui/examples/fltk && cargo build)
